#!/usr/bin/env bash
#
# Tool to synchronize versioned and user scripts in the ~/bin folder.
#
# Depends on:
# - rsync

USER_BIN="$HOME/bin"
NEST_BIN="$PWD/bin"

mkdir -p $USER_BIN

files=$(git ls-files --cached $NEST_BIN | sed 's/bin\///g')

if [[ $1 == "out" ]]; then
    echo "Syncing OUT"
    out=1
elif [[ $1 == "in" ]]; then
    echo "Syncing IN"
    out=0
else
    echo "Usage: sync <in|out>"
    echo "  in : copy scripts from \"$USER_BIN\""
    echo "  out: copy scripts to \"$USER_BIN\""
    exit
fi

if [[ $out == 1 ]]; then
    src_dir=$NEST_BIN
    dst_dir=$USER_BIN
else
    dst_dir=$NEST_BIN
    src_dir=$USER_BIN
fi

for file in $files; do
    src="$src_dir/$file"
    dst="$dst_dir/$file"
    echo "* '$src' -> '$dst'"
    cp $src $dst
done
